-- Execute UMA VEZ no SQL Editor do Supabase para habilitar o cadastro de subclasses no painel.
create table if not exists public.subclasses_catalogo (
  id bigint generated by default as identity primary key,
  classe text not null,
  nome text not null,
  criado_em timestamptz not null default now(),
  unique (classe, nome)
);
alter table public.subclasses_catalogo enable row level security;
drop policy if exists "Leitura subclasses" on public.subclasses_catalogo;
create policy "Leitura subclasses" on public.subclasses_catalogo for select to anon, authenticated using (true);
drop policy if exists "Admin gerencia subclasses" on public.subclasses_catalogo;
create policy "Admin gerencia subclasses" on public.subclasses_catalogo for all to authenticated using (true) with check (true);
grant select on public.subclasses_catalogo to anon, authenticated;
grant insert, update, delete on public.subclasses_catalogo to authenticated;
grant usage, select on sequence public.subclasses_catalogo_id_seq to authenticated;
