-- Execute UMA VEZ no SQL Editor do Supabase.
-- A vitrine continua com SELECT público apenas para produtos ativos.
alter table public.produtos_pharmagno enable row level security;

drop policy if exists "Admin pode atualizar produtos" on public.produtos_pharmagno;
create policy "Admin pode atualizar produtos"
on public.produtos_pharmagno
for update
to authenticated
using (true)
with check (true);

grant update on table public.produtos_pharmagno to authenticated;

-- Não liberamos INSERT/DELETE anônimo. O painel exige login do Supabase Auth.

-- V2: regras de promoção por classe/subclasse
create table if not exists public.promocoes_catalogo (
  id bigint generated by default as identity primary key,
  nome text not null,
  tipo text not null check (tipo in ('classe','subclasse')),
  classe text,
  subclasse text,
  desconto numeric(5,2) not null check (desconto >= 0 and desconto <= 100),
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);
alter table public.promocoes_catalogo enable row level security;
drop policy if exists "Leitura publica promocoes catalogo" on public.promocoes_catalogo;
create policy "Leitura publica promocoes catalogo" on public.promocoes_catalogo for select to anon, authenticated using (ativo = true);
drop policy if exists "Admin gerencia promocoes catalogo" on public.promocoes_catalogo;
create policy "Admin gerencia promocoes catalogo" on public.promocoes_catalogo for all to authenticated using (true) with check (true);
grant select on public.promocoes_catalogo to anon, authenticated;
grant insert, update, delete on public.promocoes_catalogo to authenticated;
grant usage, select on sequence public.promocoes_catalogo_id_seq to authenticated;

-- V3 (04/10/2026): promoção também pode ser aplicada a um produto específico.
alter table public.promocoes_catalogo add column if not exists produto_id bigint;
alter table public.promocoes_catalogo drop constraint if exists promocoes_catalogo_tipo_check;
alter table public.promocoes_catalogo add constraint promocoes_catalogo_tipo_check check (tipo in ('classe','subclasse','produto'));
